### ISSUE TITLE
 docker pull failing with default tag

### ISSUE THREAD

**Issue by karlgunst** [forcedotcom/salesforcedx-docker#34] opened 2021-08-12 22:42 UTC
Running `docker pull salesforce/salesforcedx` or `docker pull salesforce/salesforcedx:latest` results in the error shown below

```
Error response from daemon: manifest for salesforce/salesforcedx:latest not found: 
manifest unknown: manifest unknown
```

This was working earlier today

**Comment by nedkov** [comment] 2021-08-16 06:37
Also problem for us. Possible workaround https://salesforce.stackexchange.com/questions/354209/manifest-for-salesforce-salesforcedxlatest-not-found-manifest-unknown-manifes

**Comment by eugeneniemand** [comment] 2021-08-16 08:04
Experiencing the same problem with latest/default just pinning to 7.113.0-full for now to continue working

**Comment by cristiand391** [comment] 2021-08-23 14:29
Thanks for writing in, going to close this as duplicate of https://github.com/forcedotcom/cli/issues/1136.

**Closed by cristiand391** 2021-08-23 14:29 UTC
